test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
  - django

pylint:
  disable:
    - star-args
    - too-few-public-methods
    - too-many-ancestors
    - too-many-locals
    - too-many-arguments
  options:
    const-rgx: (([A-Z_][A-Z0-9_]*)|([a-z_][a-z0-9_]*)|(__.*__))$
