language: python

python:
  - 2.7
  - 3.4
  - 3.5

services:
  - postgresql
  - memcached

env:
  - DJANGO=1.8.5

before_install:
  - export DJANGO_SETTINGS_MODULE=sso.settings
  - export PYTHONPATH=$HOME/builds/DheerendraRathor/ldap-oauth2

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/py2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements/py3.txt; fi
  - pip install django==$DJANGO --quiet
  - pip install python-coveralls

script:
  - cp sso/settings_user.py.sample sso/settings_user.py
  - python manage.py check
  - isort -rc --check-only --diff .
  - python manage.py collectstatic --noinput
  - python manage.py migrate --noinput
  - coverage run --source '.' manage.py test

after_success:
  - coveralls
