# Generated by Django 3.0.6 on 2020-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200905_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Application satisfies all policy constraints. READ THE GYMKHANA PROFILES/SSO POLICY CAREFULLY BEFORE VERIFICATION'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Application satisfies all policy constraints. READ THE GYMKHANA PROFILES/SSO POLICY CAREFULLY BEFORE VERIFICATION'),
        ),
    ]
