# Generated by Django 3.0.6 on 2020-09-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200905_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_beta',
            field=models.BooleanField(default=False, help_text='Allow unlimited users without verification. A development warning will be displayed to the user'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='is_beta',
            field=models.BooleanField(default=False, help_text='Allow unlimited users without verification. A development warning will be displayed to the user'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Application satisfies all policy constraints. Read the Gymkhana Profiles/SSO policy before verification'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Application satisfies all policy constraints. Read the Gymkhana Profiles/SSO policy before verification'),
        ),
    ]
